version: '3.3'    

services:

  web:
    build:
      context: ./
      dockerfile: ./docker/web-server/Dockerfile
    container_name: spa-web
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - API_HOST=api
      - API_PORT=6000
    depends_on:
      - api
    links:
      - api

  api:
    build:
      context: ./
      dockerfile: ./docker/api-server/Dockerfile
    container_name: spa-api
    restart: unless-stopped
    ports:
      - "6000"
    environment:
      - DB_URI=mongodb://db:27017/spa
    depends_on:
      - db
    links:
      - db

  db:
    image: mongo
    container_name: spa-mongodb
    restart: unless-stopped
    volumes:
      - ./docker/db:/data/db
