version: "2"

services:

  web:
    build: ./docker/web
    container_name: web
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db
    environment:
      - FOO=bar

  db:
    image: mongodb
    container_name: web-mongodb
    restart: unless-stopped
    volumes:
      - ./docker/db:/data/db
