version: "2"

services:

  web:
    build: ./web
    container_name: web
    restart: unless-stopped
    ports:
      - "5000:5000"
    depends_on:
      - db
    links:
      - db
    environment:
      - FOO=bar
  api:
    build: ./api
    container_name: api
    restart: unless-stopped
    ports:
      - "6000:6000"

  db:
    image: mongodb
    container_name: web_mongodb
    restart: unless-stopped
    volumes:
      - ./docker/db:/data/db
